/**
 * Snapshot of the static audit run on every `exportCsv()` call site.
 * Generated by /tmp/audit-csv.mjs (see chat history). Update this file when
 * a new calculator gains CSV export.
 *
 * Each entry mirrors what `buildCsvContent()` would emit for that call:
 *   - filename pattern (using a frozen 2026-04-21 12:00 timestamp for display)
 *   - first 5 banner lines, joined with \n
 *   - pass = whether all 5 banner lines + blank separator are present
 */
export interface CsvAuditEntry {
  file: string;
  calculator: string;
  title: string;
  scenario: string;
  units: string;
  blocks: number;
  filenameSample: string;
  banner: string;
  pass: boolean;
}

const STAMP = "202604211200";
const fname = (slug: string, suffix?: string) =>
  `uscalculator-${slug}${suffix ? `-${suffix}` : ""}-${STAMP}.csv`
    .replace(/[^a-z0-9-]+/gi, "-")
    .replace(/-+/g, "-");

const banner = (title: string, scenario: string, units: string) =>
  [
    `# USCalculator — ${title}`,
    `# Scenario: ${scenario}`,
    `# Units: ${units}`,
    `# Generated: <ISO timestamp>`,
    `# Source: <window.location.href>`,
  ].join("\n");

export const CSV_AUDIT: CsvAuditEntry[] = [
  {
    file: "src/pages/calculators/Mortgage.tsx",
    calculator: "mortgage",
    title: "Mortgage Calculator",
    scenario: "$400,000 home, 30yr @ 6.5%",
    units: "USD",
    blocks: 1,
    filenameSample: fname("mortgage", "yearly-30yr"),
    banner: banner("Mortgage Calculator", "$400,000 home, 30yr @ 6.5%", "USD"),
    pass: true,
  },
  {
    file: "src/pages/calculators/Mortgage.tsx",
    calculator: "mortgage",
    title: "Mortgage Calculator",
    scenario: "$400,000 home, 30yr @ 6.5%",
    units: "USD",
    blocks: 1,
    filenameSample: fname("mortgage", "monthly"),
    banner: banner("Mortgage Calculator", "$400,000 home, 30yr @ 6.5%", "USD"),
    pass: true,
  },
  {
    file: "src/pages/calculators/Loan.tsx",
    calculator: "loan",
    title: "Loan Calculator",
    scenario: "$200,000 / 15yr / 6%",
    units: "USD",
    blocks: 1,
    filenameSample: fname("loan", "yearly"),
    banner: banner("Loan Calculator", "$200,000 / 15yr / 6%", "USD"),
    pass: true,
  },
  {
    file: "src/pages/calculators/Loan.tsx",
    calculator: "loan",
    title: "Loan Calculator",
    scenario: "$200,000 / 15yr / 6%",
    units: "USD",
    blocks: 1,
    filenameSample: fname("loan", "monthly"),
    banner: banner("Loan Calculator", "$200,000 / 15yr / 6%", "USD"),
    pass: true,
  },
  {
    file: "src/pages/calculators/DebtPayoff.tsx",
    calculator: "debt-payoff",
    title: "Debt Payoff Calculator",
    scenario: "$10,000 balance @ 18% APR, $300/mo",
    units: "USD",
    blocks: 1,
    filenameSample: fname("debt-payoff"),
    banner: banner("Debt Payoff Calculator", "$10,000 balance @ 18% APR, $300/mo", "USD"),
    pass: true,
  },
  {
    file: "src/pages/calculators/Retirement.tsx",
    calculator: "retirement",
    title: "Retirement Calculator",
    scenario: "Age 30 → 65, $50,000 saved, $500/mo",
    units: "USD",
    blocks: 1,
    filenameSample: fname("retirement"),
    banner: banner("Retirement Calculator", "Age 30 → 65, $50,000 saved, $500/mo", "USD"),
    pass: true,
  },
  {
    file: "src/pages/calculators/math/Average.tsx",
    calculator: "average",
    title: "Average Calculator",
    scenario: "10 values, mean 42.5",
    units: "unitless",
    blocks: 2,
    filenameSample: fname("average"),
    banner: banner("Average Calculator", "10 values, mean 42.5", "unitless"),
    pass: true,
  },
  {
    file: "src/pages/calculators/math/Stats.tsx",
    calculator: "statistics",
    title: "Statistics Calculator",
    scenario: "10 values",
    units: "unitless",
    blocks: 2,
    filenameSample: fname("statistics"),
    banner: banner("Statistics Calculator", "10 values", "unitless"),
    pass: true,
  },
  {
    file: "src/pages/calculators/math/StdDev.tsx",
    calculator: "standard-deviation",
    title: "Standard Deviation Calculator",
    scenario: "10 values, mean 42.5",
    units: "unitless",
    blocks: 2,
    filenameSample: fname("standard-deviation"),
    banner: banner("Standard Deviation Calculator", "10 values, mean 42.5", "unitless"),
    pass: true,
  },
  {
    file: "src/pages/calculators/math/Sequence.tsx",
    calculator: "number-sequence",
    title: "Number Sequence Calculator",
    scenario: "arithmetic sequence, 20 terms",
    units: "unitless",
    blocks: 2,
    filenameSample: fname("number-sequence"),
    banner: banner("Number Sequence Calculator", "arithmetic sequence, 20 terms", "unitless"),
    pass: true,
  },
  {
    file: "src/pages/calculators/math/RandomNumber.tsx",
    calculator: "random-number",
    title: "Random Number Generator",
    scenario: "10 integers in [1, 100], unique",
    units: "unitless",
    blocks: 2,
    filenameSample: fname("random-number"),
    banner: banner("Random Number Generator", "10 integers in [1, 100], unique", "unitless"),
    pass: true,
  },
  {
    file: "src/pages/calculators/math/Probability.tsx",
    calculator: "probability",
    title: "Probability Calculator",
    scenario: "P(A)=0.4, P(B)=0.3",
    units: "probability (0–1)",
    blocks: 1,
    filenameSample: fname("probability"),
    banner: banner("Probability Calculator", "P(A)=0.4, P(B)=0.3", "probability (0–1)"),
    pass: true,
  },
  {
    file: "src/pages/calculators/math/PermComb.tsx",
    calculator: "permutation-combination",
    title: "Permutation & Combination Calculator",
    scenario: "n=10, r=3",
    units: "count",
    blocks: 2,
    filenameSample: fname("permutation-combination", "n10"),
    banner: banner("Permutation & Combination Calculator", "n=10, r=3", "count"),
    pass: true,
  },
  {
    file: "src/pages/calculators/math/Matrix.tsx",
    calculator: "matrix",
    title: "Matrix Calculator",
    scenario: "Operation: add",
    units: "scalar",
    blocks: 3,
    filenameSample: fname("matrix", "add"),
    banner: banner("Matrix Calculator", "Operation: add", "scalar"),
    pass: true,
  },
];

export const CSV_AUDIT_SUMMARY = {
  total: CSV_AUDIT.length,
  passing: CSV_AUDIT.filter((e) => e.pass).length,
  failing: CSV_AUDIT.filter((e) => !e.pass).length,
  files: new Set(CSV_AUDIT.map((e) => e.file)).size,
  calculators: new Set(CSV_AUDIT.map((e) => e.calculator)).size,
};
